## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: (Internal) CI MacOS

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:

  ## Build Jobs ##

  build-macos:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      cmd: |
        .github/scripts/build.sh
      artifact-out: build-macos
      artifact-path: build

  build-macos-arm:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "arm" ]'
      cmd: |
        .github/scripts/build.sh
      artifact-out: build-macos-arm
      artifact-path: build

  ## Functional Test Jobs ##

  test-macos:
    needs: build-macos
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "x86_64" ]'
      cmd: |
        export DYLD_FALLBACK_LIBRARY_PATH=./build:$DYLD_FALLBACK_LIBRARY_PATH
        ./build/rkcommon_test_suite
      artifact-in: build-macos

  test-macos-arm:
    needs: build-macos-arm
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      runs-on: '[ "macOS", "build", "arm" ]'
      cmd: |
        export DYLD_FALLBACK_LIBRARY_PATH=./build:$DYLD_FALLBACK_LIBRARY_PATH
        ./build/rkcommon_test_suite
      artifact-in: build-macos-arm
