## Copyright 2024 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI Linux

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-rocky-8:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    steps:
    - name: Install packages
      run: |
        echo "Installing build dependencies..."
        dnf update -y
        dnf install -y git cmake tbb-devel
        dnf group install -y "Development Tools"

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build
      run: | 
        mkdir build
        cd build
        cmake -D CMAKE_INSTALL_PREFIX=`pwd`/install ..
        make -j`nproc` install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-rocky-8
        path: build/install

  test-rocky-8:
    needs: build-rocky-8
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    steps:
    - name: Install packages
      run: |
        echo "Installing runtime dependencies..."
        dnf update -y
        dnf install -y tbb

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-rocky-8

    - name: Test
      run: |
        # Adding execution bit to binaries is needed since upload/download GHA is using zip compression
        # and it can't preserve files permissions - https://github.com/actions/upload-artifact/issues/38
        chmod +x ./bin/*
        LD_LIBRARY_PATH=./lib64/ ./bin/rkcommon_test_suite -d yes


  build-ubuntu-2204:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
    - name: Install packages
      run: |
        echo "Installing build dependencies..."
        apt update
        apt upgrade -y
        apt install -y build-essential cmake git libtbb2-dev

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D CMAKE_INSTALL_PREFIX=`pwd`/install ..
        make -j`nproc` install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-ubuntu-2204
        path: build/install


  test-ubuntu-2204:
    needs: build-ubuntu-2204
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
    - name: Install packages
      run: |
        echo "Installing runtime dependencies..."
        apt update
        apt upgrade -y
        apt install -y libtbb2

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-ubuntu-2204

    - name: Test
      run: |
        # Adding execution bit to binaries is needed since upload/download GHA is using zip compression
        # and it can't preserve files permissions - https://github.com/actions/upload-artifact/issues/38
        chmod +x ./bin/*
        
        LD_LIBRARY_PATH=./lib/ ./bin/rkcommon_test_suite -d yes